src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C501_IS_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Intake_Services_Checkin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Box_Size__c</fullName>
        <label>Bag/Box Size</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Points_Remaining__c</fullName>
        <label>Points Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intake Services Current Checkins</label>
</CustomObject>

src/classes/IntakeServicesStatsTest.cls
@isTest
public with sharing class IntakeServicesStatsTest {

	@isTest
	private static void testIntakeServicesStats() {

		// insert a household and a visit for today
        Account hh = new Account(
			Name = 'Test Account',
			C501_IS_Inactive__c = false
			);

		// insert a contact
        Contact contact = new Contact(
			Lastname = 'Test Lastname'
			);

        hh = IntakeServices.saveHousehold(hh);

		Intake_Services_Checkin__c checkin1 = new Intake_Services_Checkin__c(
			Name = hh.Id,
            Points_Remaining__c = 15,
            Box_Size__c = 'small',
            Check_In_Time__c = Datetime.now()
        );

		insert checkin1;
		
        Map<String, Integer> commU = new Map<String, Integer>();
        Id cVId = IntakeServices.logVisit(hh.Id, contact.Id, 'small', 1.5, 5, commU, 'These are notes', new List<String> {'Housing Intake'}, new List<String>{'Childcare'});

		ApexPages.CurrentPage().getParameters().put('tfcode','TODAY');
		IntakeServicesStats fbs = new IntakeServicesStats();
		fbs.loadStats();
		fbs.queryStats('TODAY');
	}

}