src/objects/Intake_Referrals__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of items for intake referrals.</description>
    <fields>
        <fullName>Locations__c</fullName>
        <description>Comma separated list of locations</description>
        <inlineHelpText>Comma separated list of locations</inlineHelpText>
        <label>Locations</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Column__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Column</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used during the intake process.</inlineHelpText>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Intake Referrals</label>
</CustomObject>

src/objects/Intake_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of items for intake services.</description>
    <fields>
        <fullName>Locations__c</fullName>
        <description>Comma separated list of locations</description>
        <inlineHelpText>Comma separated list of locations</inlineHelpText>
        <label>Locations</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Column__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Column</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used during the intake process.</inlineHelpText>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Intake Services</label>
</CustomObject>

src/objects/Intake_Services_Box_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of family-size thresholds for different intake services bag or box types. Names should match drop-down list in Visit object.</description>
    <fields>
        <fullName>Minimum_Family_Size__c</fullName>
        <label>Minimum Family Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intake Services Bag/Box Settings</label>
</CustomObject>

src/objects/Intake_Services_Commodity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of items for which the intake services tracks monthly limits and usage - for example, you get up to 3 boxes of eggs per month.</description>
    <fields>
        <fullName>Allow_Overage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff will be alerted when clients use more than the limit, but can choose to overlook the warning.</inlineHelpText>
        <label>Allow Overage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locations__c</fullName>
        <description>Comma separated list of locations</description>
        <inlineHelpText>Comma separated list of locations</inlineHelpText>
        <label>Locations</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Limit__c</fullName>
        <label>Monthly Limit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intake Services Commodity</label>
</CustomObject>

src/objects/Intake_Services_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General settings for intake services application</description>
    <fields>
        <fullName>Allow_Box_Size_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff has the option to specify the box size to provide, overriding the default for the family size.</inlineHelpText>
        <label>Allow Bag/Box Size Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Overage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff can override the alert that monthly point or visit limits have been exceeded.</inlineHelpText>
        <label>Allow Overage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_in_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if your intake services requires clients to check in before shopping and check out afterward</inlineHelpText>
        <label>Check-in Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Base_Points__c</fullName>
        <inlineHelpText>Number of monthly points for a one-person household.  Leave blank if you do not limit points.</inlineHelpText>
        <label>Monthly Base Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Points_Per_Adult__c</fullName>
        <inlineHelpText>Additional monthly points per adult over one.</inlineHelpText>
        <label>Monthly Points Per Adult</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Points_Per_Child__c</fullName>
        <inlineHelpText>Additional monthly points per child in household.</inlineHelpText>
        <label>Monthly Points Per Child</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proof_of_Address_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to require proof of address for new client households.</inlineHelpText>
        <label>Proof of Address Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proof_of_Address_Update_Interval__c</fullName>
        <inlineHelpText>Number of months after which updated proof of address is required for existing households.</inlineHelpText>
        <label>Proof of Address Update Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proof_of_Infant_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proof of Infant Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Require_Unique_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to prevent users from adding duplicate addresses.  If unchecked, users are still alerted when entering a duplicate, but can choose to continue.</inlineHelpText>
        <label>Require Unique Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Id__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to show the Id field for member lookup.  If unchecked, an Id field will show.</inlineHelpText>
        <label>Show Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_IS_Tags__c</fullName>
        <description>Semi-colon delimited list of tags for client households.</description>
        <inlineHelpText>Semi-colon delimited list of tags for client households. Example:  Special Diet; Spanish Speaker</inlineHelpText>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Checkout_Weight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you track checkout weight.</inlineHelpText>
        <label>Track Checkout Weight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Points__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you track monthly points. If unchecked, application will track bag/box size instead.</inlineHelpText>
        <label>Track Points</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Alert__c</fullName>
        <inlineHelpText>Optional alert that will be shown prominently on Intake Services intake tab.</inlineHelpText>
        <label>Welcome Alert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Message__c</fullName>
        <inlineHelpText>Shown at top of Intake Services intake tab</inlineHelpText>
        <label>Welcome Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Intake Services Settings</label>
</CustomObject>

src/classes/IntakeServicesSettings.cls
public with sharing class IntakeServicesSettings {

    /**************************************************************************
    * The pattern is to create a static property for each settings object
    * and provide defaults if it is a test. Each setting will be instantiated
    * only once per transaction.
    *
    * To refer to a setting in the first section below, use:
    *   IntakeServicesSettings.general.Monthly_Visit_Limit__c
    *
    * For a list setting, specify the value you want:
    *   IntakeServicesSettings.commodity('Bread').Monthly_Limit__c
    *
    ***************************************************************************/

    public static Intake_Services_Settings__c general {
        get {
            if (general == null) {
                general = Intake_Services_Settings__c.getOrgDefaults();
                if (Test.isRunningTest()) {
                    // defaults for testing
                    general.Allow_Box_Size_Override__c = false;
                    general.Allow_Overage__c = false;
                    general.Monthly_Base_Points__c = 30;
                    general.Monthly_Points_Per_Adult__c = 10;
                    general.Monthly_Points_Per_Child__c = 10;
                    general.Check_in_Required__c = false;
                    general.Proof_of_Address_Required__c = true;
                    general.Proof_of_Address_Update_Interval__c = 12;
                    general.Require_Unique_Address__c = false;
                    general.Show_Id__c = false;
                    general.Proof_of_Infant_Required__c = true;
                    general.Track_Checkout_Weight__c = true;
                    general.Track_Points__c = true;
                    general.C501_IS_Tags__c = 'Special Diet; Spanish Speaker';
                    general.Welcome_Alert__c = 'Hello!';
                    general.Welcome_Message__c = 'Welcome to the intake services.';
                }
            }
            return general;
        }
        set;
    }

    public static list<Intake_Services_Commodity__c> commodities {
        get {
            if (commodities == null) {
                commodities = (!Test.isRunningTest()) ?
                    [select name, Monthly_Limit__c, Allow_Overage__c, Locations__c from Intake_Services_Commodity__c order by Sort_Order__c, name] :
                    new List<Intake_Services_Commodity__c>{
                        new Intake_Services_Commodity__c(
                            Name = 'Meat',
                            Monthly_Limit__c = 5,
                            Sort_Order__c = 0,
                            Allow_Overage__c = false,
                            Locations__c = 'Seattle' ),
                        new Intake_Services_Commodity__c(
                            Name = 'Bread',
                            Monthly_Limit__c = 3,
                            Sort_Order__c = 1,
                            Allow_Overage__c = true,
                            Locations__c = 'Seattle' )
                    };
            }

            System.debug('*****IntakeServicesSettings::commodities ' + commodities);
            return commodities;
        }
        set;
    }

    public static list<Intake_Services__c> services {
        get {
            if (services == null) {
                services = (!Test.isRunningTest()) ?
                    [select name, Sort_Order__c, Locations__c, Column__c, Selected__c from Intake_Services__c order by Sort_Order__c, name] :
                    new List<Intake_Services__c>{
                        new Intake_Services__c(
                            Name = 'Foodbank',
                            Column__c = 1,
                            Sort_Order__c = 0,
                            Locations__c = 'Seattle' ),
                        new Intake_Services__c(
                            Name = 'Housing',
                            Column__c = 2,
                            Sort_Order__c = 1,
                            Locations__c = 'Seattle' )
                    };
            }

            System.debug('*****IntakeServicesSettings::services ' + services);
            return services;
        }
        set;
    }

    public static list<Intake_Referrals__c> referrals {
        get {
            if (referrals == null) {
                referrals = (!Test.isRunningTest()) ?
                    [select name, Sort_Order__c, Locations__c, Column__c, Selected__c from Intake_Referrals__c order by Sort_Order__c, name] :
                    new List<Intake_Referrals__c>{
                        new Intake_Referrals__c(
                            Name = 'Dentist',
                            Column__c = 1,
                            Sort_Order__c = 0,
                            Locations__c = 'Seattle' ),
                        new Intake_Referrals__c(
                            Name = 'Doctor',
                            Column__c = 2,
                            Sort_Order__c = 1,
                            Locations__c = 'Seattle' )
                    };
            }

            System.debug('*****IntakeServicesSettings::referrals ' + referrals);
            return referrals;
        }
        set;
    }

    public static list<Intake_Services_Box_Settings__c> boxes {
        get {
            if (boxes == null) {
                boxes = (!Test.isRunningTest()) ?
                    [select name, Minimum_Family_Size__c from Intake_Services_Box_Settings__c order by Minimum_Family_Size__c asc nulls last, name] :
                    new List<Intake_Services_Box_Settings__c>{
                        new Intake_Services_Box_Settings__c(
                            Name = 'Small',
                            Minimum_Family_Size__c = 1 ),
                        new Intake_Services_Box_Settings__c(
                            Name = 'Large',
                            Minimum_Family_Size__c = 3 ),
                        new Intake_Services_Box_Settings__c(
                            Name = 'No Cook' )
                    };
            }
            return boxes;
        }
        set;
    }
}